Vova and Sergiy podarasy
VolodymyrKirichenko/layout_my-bike pull request #3
Opened 2022-09-29 16:04 UTC by VolodymyrKirichenko

2022-09-30 12:11 UTC, SerhiiKirik commented on .github/workflows/test.yml
> +>>>>>>> Stashed changes
why you add this?

2022-09-30 12:12 UTC, SerhiiKirik commented on .linthtmlrc.json
> +  ],
and this?

2022-09-30 13:30 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +        line-height: 100%;
Change this to px in all cases

2022-09-30 13:32 UTC, SerhiiKirik commented on src/styles/blocks/about.scss
> +    letter-spacing: -1.5px;
you use this 5 times, you can create variables for this

2022-09-30 13:33 UTC, SerhiiKirik commented on src/styles/blocks/about.scss
> +
mixin for this

2022-09-30 13:33 UTC, SerhiiKirik commented on src/styles/blocks/about.scss
> +    line-height: 140%;
px

2022-09-30 13:34 UTC, SerhiiKirik commented on src/styles/blocks/about.scss
> +    display: block;
p tag has display: block by defauld

2022-09-30 13:35 UTC, SerhiiKirik commented on src/styles/blocks/compare.scss
> +    line-height: 32px;
use this text mixin here

2022-09-30 13:35 UTC, SerhiiKirik commented on src/styles/blocks/compare.scss
> +    text-transform: capitalize;
DRY - you use this 2 times

2022-09-30 13:36 UTC, SerhiiKirik commented on src/styles/blocks/contact-us.scss
> +      text-shadow: 0 0 10px #fff;
```suggestion
      color: $colorWhite;
      text-shadow: 0 0 10px $colorWhite;

```

2022-09-30 13:36 UTC, SerhiiKirik commented on src/styles/blocks/contact-us.scss
> +    color: #fff;
```suggestion
    color: $colorWhite;

```

2022-09-30 13:40 UTC, SerhiiKirik commented on src/styles/blocks/form.scss
> +    display: block;
why block?

2022-09-30 13:41 UTC, SerhiiKirik commented on src/styles/blocks/form.scss
> +      border: 1px solid #d5d7de;
```suggestion
    background: $variables;
    border: 1px solid transparent;
    border-radius: 40px;

    &:hover {
      background: $variables;
      border: 1px solid $variables;

```

2022-09-30 13:41 UTC, SerhiiKirik commented on src/styles/blocks/grid.scss
> +
```suggestion
```

2022-09-30 13:43 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +        transition-duration: 0.3s;
better will be if you use transition: opacity 0.3s

2022-09-30 13:43 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +    transition-duration: 0.3s;
the same

2022-09-30 13:43 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +    font-family: Poppins, sans-serif;
```suggestion
```

2022-09-30 13:44 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +  background-color: #c2c2c2;
```suggestion
  background-color: $variables;

```

2022-09-30 13:44 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    padding: 29px 20px 20px;
```suggestion
    max-width: 1260px;
    width: 100%;
    height: 100vh;
    margin: 0 auto;
    padding: 29px 20px 20px;

```

2022-09-30 13:44 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    max-width: 1020px;
```suggestion
  &__list {
    max-width: 1020px;
    margin-bottom: 40px;
    padding: 0;
```

2022-09-30 13:44 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    color: #1d1d1d;
```suggestion
    color: $variables;

```

2022-09-30 13:45 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    transition-duration: 0.3s;
the same

2022-09-30 13:45 UTC, SerhiiKirik commented on src/styles/blocks/page.scss
> +  scroll-behavior: smooth;
```suggestion
  color: $color-white;
  
  scroll-behavior: smooth;

```

2022-09-30 13:45 UTC, SerhiiKirik commented on src/styles/blocks/page.scss
> +    background-color: #1d1d1d;
```suggestion
    background-color: $variables;

```

2022-09-30 13:45 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +    border-radius: 8px;
split it

2022-09-30 13:47 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +      padding-bottom: 100%;
split

2022-09-30 13:47 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +    transition: 0.3s;
just transition?

2022-09-30 13:47 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +    line-height: 140%;
```suggestion
    margin: 0 auto 8px;
    
    font-weight: 700;
    font-size: 24px;
    line-height: 140%;
```

2022-09-30 13:49 UTC, SerhiiKirik commented on src/styles/utils/_mixins.scss
> +    pointer-events: none;
sort it out

2022-09-30 13:49 UTC, SerhiiKirik approved these changes
Well done 🔥  ( It's reject )0
Let's fix some problems

2022-10-04 10:16 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +        transition-duration: 0.3s;
r
```suggestion
        transition: opacity 0.3s;
```

2022-10-04 10:36 UTC, SerhiiKirik requested changes
Well done, almost. let's fix some problem

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/about.scss
> +    letter-spacing: -1.5px;
???????????????

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/utils/_typography.scss
> +  letter-spacing: -1.5px;
```suggestion
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/button.scss
> +  transition: all 0.3s;
transition-duration: 0.3 - the same
use only param that you use

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  transition-duration: 0.3s;
```suggestion
  grid-row: 1;

  max-width: 324px;
  margin: 0 auto 24px;
  padding: 10px;

  border: 1px solid transparent;
  border-radius: 10px;
  background-color: $color-dark-black;
  box-shadow: 1px 4px 16px rgba(232, 232, 240, 0.4);

  transition-duration: 0.3s;

```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  transition-duration: 0.3s;
transition-duration: 0.3s; ???

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +    @extend %t-poppins-24-bold;
```suggestion
    @extend %t-poppins-24-bold;
    
    margin: 0 auto 8px;
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +    @extend %t-poppins-24-bold;
in ALL CASES!!!

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +        color: $color-white;
split this

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +        letter-spacing: 1.5px;
1.5 or -1.5?
```suggestion
        letter-spacing: 1.5px;

```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    margin-bottom: 16px;
```suggestion
    width: max-content;
    margin-bottom: 16px;

    font-weight: 600;
    font-size: 16px;
    line-height: 27px;
    color: $color-dark-black;
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    padding: 0 0 8px;
```suggestion
    display: inline-block;
    
    padding: 0 0 8px;

```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +    border-radius: 8px;
```suggestion
    width: 100%;
    
    border-radius: 8px;

```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/blocks/place.scss
> +    transition-duration: 0.3s;
🤯

2022-10-04 10:36 UTC, SerhiiKirik commented on src/styles/utils/_mixins.scss
> +    pointer-events: none;
```suggestion
    height: 2px;
    
    border-radius: 8px;
    background-color: #{$color};
    
    transition: scale 0.3s;
    transform: scale(0);
    pointer-events: none;
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/index.html
> +            >
```suggestion
            <div class="card grid__item-desktop--1-4">
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/index.html
> +            >
```suggestion
            <div class="card grid__item-desktop--9-12">
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/index.html
> +                         class="place__photo">
```suggestion
                    <img src="./images/photos/photo1.jpg"
                         alt="Photo 1"
                         class="place__photo"
                     >
```

2022-10-04 10:36 UTC, SerhiiKirik commented on src/index.html
> +                         class="place__photo">
```suggestion
                    <img src="./images/photos/photo2.jpg"
                         alt="Photo 2"
                         class="place__photo"
                     >
```

2022-10-05 09:38 UTC, VolodymyrKirichenko commented on src/styles/blocks/header.scss
> +        letter-spacing: 1.5px;
1.5 (everything is correct here)

2022-10-05 16:51 UTC, SerhiiKirik requested changes
Good job 👍 
We are almost done with this PR
Check comments & fix problem 😉

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/button.scss
> +  transition-duration: 0.3s;
```suggestion
  transition: box-shadow 0.3s;

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/button.scss
> +
```suggestion
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  transition-duration: 0.3s;
```suggestion
  transition: transform  0.3s;

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/contact-us.scss
> +
```suggestion
    margin-bottom: 48px;

    text-align: center;

    letter-spacing: $spacing;
    
     @include onTablet {
        font-size: 48px;
        line-height: 48px;
    }
  }
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +
```suggestion

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +
```suggestion

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +
```suggestion

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/header.scss
> +    transition-duration: 0.3s;
Do you ignore me?
```suggestion
    transition: background-image 0.3s;

```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +
```suggestion
    height: 100vh;
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +
```suggestion
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +    transition-duration: 0.3s;
here you have to do by yourself

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +
```suggestion
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/blocks/menu.scss
> +
```suggestion
```

2022-10-05 16:51 UTC, SerhiiKirik commented on src/styles/utils/_mixins.scss
> +    transition: scale, 0.3s;
```suggestion
    transition: transform 0.3s;
```

2023-02-08 20:04 UTC, merged